name: Manual Release

on:
  workflow_dispatch:
    inputs:
      increment:
        type: string
        description: "Must be: patch, minor, major, pre* or <version>"
        required: true
        default: "patch"

jobs:
  manual-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
      packages: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup GIT
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 20.x

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package.json', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: |
          if [ -f yarn.lock ]; then
            yarn install --frozen-lockfile
          else
            yarn install --no-lockfile
          fi

      - name: Release
        run: npx release-it --ci --increment ${{ github.event.inputs.increment }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Read released version
        id: released_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=v$VERSION" >> $GITHUB_OUTPUT

      - name: Publish in NPM (as `libzapitu-rf` and aliases)
        run: |
          npm publish --access public --//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npx json -I -f package.json -e "this.name='libzapitu'"
          npm publish --access public --//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npx json -I -f package.json -e "this.name='zapitu'"
          npm publish --access public --//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
          npx json -I -f package.json -e "this.name='zapitu-rf'"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Generate Changelog
        id: generate_changelog
        run: |
          changelog=$(npm run changelog:last --silent)
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "${changelog}" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Make Package
        run: npm pack

      - name: Rename Pack
        run: mv *.tgz libzapitu-rf.tgz

      - name: Create Release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.released_version.outputs.tag }}
          commitish: ${{ github.sha }}
          name: ${{ steps.released_version.outputs.tag }}
          body: ${{ steps.generate_changelog.outputs.changelog }}
          draft: false
          prerelease: false
          files: >
            libzapitu-rf.tgz
          gzip: folders
          allow_override: true
